/*创建数据库*/
DROP TABLE IF EXISTS  `person`;

CREATE TABLE `person` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '人员id',
  `name` VARCHAR(25) DEFAULT NULL COMMENT '姓名',
  `phone` VARCHAR(25) DEFAULT NULL COMMENT '联系电话',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT person VALUES (1 ,'张三','18918881888');
INSERT person VALUES (2 ,'李四','18918882884');
INSERT person VALUES (3 ,'王五','18918883885');