##用json的方式写配置
##服务端口
server:
  port: 9080
  servlet:
    context-path: /springboot

## mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# Redis 配置
  redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址，默认localhost
        host: 127.0.0.1
        # 端口 默认6379
        port: 6379
        # 密码 默认空
        password: bnh_2e06


## Mybatis
mybatis:
  typeAliasesPackage: com.smarts.springboot.entity
  mapperLocations: classpath:mapper/*.xml
